# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 480)
        self.d = QtWidgets.QLineEdit(Dialog)
        self.d.setGeometry(QtCore.QRect(120, 270, 231, 20))
        self.d.setObjectName("d")
        self.c = QtWidgets.QLineEdit(Dialog)
        self.c.setGeometry(QtCore.QRect(120, 200, 231, 20))
        self.c.setObjectName("c")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(120, 310, 91, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(120, 370, 101, 16))
        self.label_6.setObjectName("label_6")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(120, 170, 101, 16))
        self.label_3.setObjectName("label_3")
        self.b = QtWidgets.QLineEdit(Dialog)
        self.b.setGeometry(QtCore.QRect(120, 130, 231, 20))
        self.b.setObjectName("b")
        self.f = QtWidgets.QLineEdit(Dialog)
        self.f.setGeometry(QtCore.QRect(120, 400, 231, 20))
        self.f.setObjectName("f")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(120, 100, 91, 16))
        self.label_2.setObjectName("label_2")
        self.ok_btn = QtWidgets.QPushButton(Dialog)
        self.ok_btn.setGeometry(QtCore.QRect(410, 190, 151, 41))
        self.ok_btn.setObjectName("ok_btn")
        self.e = QtWidgets.QLineEdit(Dialog)
        self.e.setGeometry(QtCore.QRect(120, 340, 231, 20))
        self.e.setObjectName("e")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(120, 30, 81, 16))
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(120, 240, 111, 16))
        self.label_4.setObjectName("label_4")
        self.a = QtWidgets.QLineEdit(Dialog)
        self.a.setGeometry(QtCore.QRect(120, 60, 231, 20))
        self.a.setObjectName("a")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_5.setText(_translate("Dialog", "цена"))
        self.label_6.setText(_translate("Dialog", "объем упаковки"))
        self.label_3.setText(_translate("Dialog", "молотый/в зернах"))
        self.label_2.setText(_translate("Dialog", "степень обжарки"))
        self.ok_btn.setText(_translate("Dialog", "Осуществить"))
        self.label.setText(_translate("Dialog", "название сорта"))
        self.label_4.setText(_translate("Dialog", "описание вкуса"))
